### ISSUE TITLE
Use of reserved word 'let' in strict mode

### ISSUE THREAD

**Issue by phoet** [dialogflow/dialogflow-javascript-client#63]
adding api-ai to my testing setup with phantomjs fails with:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Use of reserved word 'let' in strict mode
  at webpack:///node_modules/api-ai-javascript/es6/ApiAiConstants.js:3:0 <- index.js:72754

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.548 secs / 0 secs)
```

looks like the prebuilts in target are not part of the npm packages, so i can't use those either :(

**Comment by Shuunen** [comment]
@phoet I use this https://github.com/genify/babel-plugin-transform-remove-strict-mode and it works well
