### ISSUE TITLE
Module build failed: Error: ENOENT: no such file or directory index.js.map

### ISSUE THREAD

**Issue by Prince7195** [dialogflow/dialogflow-javascript-client#84]
![image](https://user-images.githubusercontent.com/24829611/38159917-0b995fe8-34d1-11e8-982a-9fbf9cdc7cd9.png)

**Comment by Prince7195** [comment]
please anyone help me to solve this error

**Comment by rahulFortunekit** [comment]
Same issue,please help in this case or give me alternatives

**Comment by Prince7195** [comment]
create index.js.map inside of it, it will be resolved. For my project, it worked.

**Comment by rahulFortunekit** [comment]
How did you solved this ??

**Comment by Prince7195** [comment]
I have created the empty index.js.map file inside the node_modules at the path where the is file missing error is shown. you just create the index.js.map file inside the dialogflow-javascript-client node_module packager

**Comment by eyesurewould** [comment]
I just received the same error for ./node_modules/rxjs/_esm5/index.js which DOES exist. I simply touched the file and then the error went away and the compile worked.

Hope that helps someone.

**Comment by Pixelwelder** [comment]
So I appreciate that the above solution works, but... could someone please explain WHY it works?

**Comment by cjlaborde** [comment]
This one worked for me.
npm rebuild node-sass

**Comment by dangelion** [comment]
Delete `node_modules` folder and re-run `npm install` (or `yarn`)

**Comment by sfmajors373** [comment]
@eyesurewould This fixed it for me too!

Can someone explain why this worked???

**Comment by Diex** [comment]
I think it has to do with how the compiler runs. I didn't try but for shure if you stop ng serve and run it again it will work. it always happens when you update modules.
when you touch the file, the compiler knows it has to recompile that file. either way you fall into that error.

**Comment by shiralizadeh** [comment]
@cjlaborde
Thanks, Works for me.

**Comment by houss-x** [comment]
./node_modules/@angular/localize/fesm2015/init.js
Module build failed: Error 
 i think it's the same but i try all  solutions and nothing happend

**Comment by mohak08** [comment]
@eyesurewould worked the same way for me. Just had to touch the existing file

**Comment by DikshantNiraula** [comment]
npm install whatever package is missing or delete node_module and npm install

**Comment by Firdaus85** [comment]
@houss-x 
try running npm install @angular/localize --save

**Comment by SoftwareEngineerPalace** [comment]
> I just received the same error for ./node_modules/rxjs/_esm5/index.js which DOES exist. I simply touched the file and then the error went away and the compile worked.
> 
> Hope that helps someone.

what's "touched the file"

**Comment by Diex** [comment]
$ touch ./somefile 

https://shapeshed.com/unix-touch/

**Comment by EnzoPujol** [comment]
> Delete `node_modules` folder and re-run `npm install` (or `yarn`)

This worked for me in Vue.js

**Comment by rabia201** [comment]
restart it.

**Comment by akapei** [comment]
`npm update` should do the trick. No deleting required.

**Comment by Sanyalak-T** [comment]
thanks, akapei

**Comment by Tochi-Nwachukwu** [comment]
I had to install framer version 4.1.17.

First I ran 

npm uninstall framer

then ran

npm install framer-motion@4.1.17

I then deleted node modules and installed all the dependencies using

npm install

That worked for me

**Comment by karon-hyppolite** [comment]
Hello.
How did you solve this issue?

**Comment by Dhanush-2605** [comment]
I just restarted the application it works for me.

**Comment by zhanghuize-git** [comment]
@Dhanush-2605  your anwser solve my question , thank you

**Comment by Dhanush-2605** [comment]
@zhanghuize-git no problem...

**Comment by Mark-777-0** [comment]
+1 for restarting... thanks @Dhanush-2605

**Comment by addi786** [comment]
### Hi there everyone! 
I have read most of the comments but could not find any solution.
**For me**

> 1.  First uninstall the previous version of framer-motion
> 2.  Install framer-motion@6.2.8

### How to do this?
**To uninstall**
For Yarn `yarn remove framer-motion` and For npm `npm uninstall framer-motion` 
**To install**
For Yarn `yarn add framer-motion@6.2.8` and For npm `npm install framer-motion@6.2.8` 

I hope your problem will be solved because this works on my project.

> @Prince7195 Checkout this solution.

**Comment by sekhar094** [comment]
> create index.js.map inside of it, it will be resolved. For my project, it worked.

thank you so much :)

**Comment by Fedorov1977** [comment]
I was working in Visual Studio 2022. Closing it and restarting helper for me.
The  file was existing on the hard drive but it still gave that error until I restarted VS2022.
Thanks @Dhanush-2605 !

**Comment by Shilpakashyap** [comment]
$ npx gltfjsx brainNew4.gltf
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 brainNew4.gltf
*/


### any one know how to solve this my gltf.js file not create by this<$ npx gltfjsx brainNew4.gltf>  command  ### please help me..

**Comment by vijaydeepak-vd** [comment]
nope

**Comment by mainak-shil** [comment]
GENERATE_SOURCEMAP=false

add in .env
