### ISSUE TITLE
V2 Support

### ISSUE THREAD

**Issue by gilesbutler** [dialogflow/dialogflow-javascript-client#87]
Hey guys,

Is this library going to be updated to support the V2 API?

I get a banner in Dialogflow saying support for V1 is ending and to use V2.

Thanks

**Comment by hboylan** [comment]
Might be [deprecated](https://github.com/dialogflow/dialogflow-javascript-client/releases/tag/2.0.0-beta.21) :sob:

**Comment by gilesbutler** [comment]
:( thanks @hboylan 

Don't suppose you know of any other services that support creating a custom web ui at all?

**Comment by hboylan** [comment]
I still highly recommend Dialogflow. The community has been working to upgrade other repos in this org to V2. You can still interact with the REST API directly

**Comment by gilesbutler** [comment]
Thanks @hboylan - yeah I've really enjoyed working with the service so far. It might be a case of pushing forward with a custom implementation through the REST API then.

**Comment by hboylan** [comment]
There’s always the option of creating a serverless function that uses the Node client library. If you use a GCP Function the added latency should be low considering requests stay within Google’s network.

**Comment by gilesbutler** [comment]
Hmm good idea. Have you seen anybody do this or know of any examples at all?

**Comment by hboylan** [comment]
There are some samples in this organization’s repos that use GCP functions. There’s actually one built in to the Dialogflow Fulfillment section to help get started

**Comment by gilesbutler** [comment]
Awesome, thanks @hboylan :)
